version: '3.8'

services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  web:
    build: .
    command: gunicorn nexalink.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - ./.env

  celery:
    build: .
    command: celery -A nexalink worker -l INFO
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    env_file:
      - ./.env

  celery-beat:
    build: .
    command: celery -A nexalink beat -l INFO
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    env_file:
      - ./.env

volumes:
  postgres_data:
  static_volume:
  media_volume:
